---
title: "(la weá que sea que vayamos a hacer con la base culiá)"
subtitle: "EYP2435 - Análisis Multivariado"
format: 
  pdf: 
    include-in-header: 
      text: |
        \usepackage{amsmath}
        \usepackage{float}
    colorlinks: true
    geometry:
      - top=20mm
      - left=20mm
      - right=20mm
      - heightrounded
    fig-pos: "H"
author: 
  - name: "Sebastián Celaya"
  - name: "Camila Echeverría"
crossref:
  fig-title: Figura
  fig-prefix: Figura
  tbl-title: Tabla
  tbl-prefix: Tabla
tbl-cap-location: bottom
---

# Introducción

# Descripción de los datos

Para el desarrollo de nuestro análisis, hemos extraído diversas variables de la base de datos `Casen2017.dta`. Entre ellas, podemos destacar las siguientes variables identificadoras o clasificadoras:

- `region`: el identificador de cada región.
- `folio`: corresponde al identificador único de cada hogar. Recordemos que la Casen hace distinción entre estos y viviendas, por lo que puede haber más de un hogar por vivienda.
- `comuna`: sirve para identificar a qué comuna del país pertenece el hogar.

Luego, nos quedamos con 3 de los indicadores de pobreza que se encuentran en el cuestionario:

- `pobreza`: corresponde a la situación de pobreza por ingresos. Puede ser extremo (1), no extremo (2) o no pobre.
- `pobreza_multi_4d`: comprendiendo la pobreza multidimensional como un "concepto más allá de la falta de ingresos para la satisfacción de necesidades, sino más bien como personas que sufren carencias en las dimensiones: educación, salud, trabajo, seguridad social, vivienda y nivel de vida en general." (Gerlach V., 2018), corresponde a la pobreza en al menos 4 dimensiones.
- `pobreza_multi_5d`: en la misma línea, corresponde a la pobreza en al menos 5 de estas dimensiones.

También se utilizaron todas las variables disponibles en la sección de indicadores en el Libro de Códigos Base de Datos (Casen, 2017), las que engeneral corresponden a un resumen de los indicadores obtenidos a través de la encuesta.

Para objetos de este análisis, y a falta del conocimiento de una mejor manera de tratar estos datos, se eliminaron todos los `NA` (o respuesta en blanco) de la base, pues en ninguna variable representaban alguna información significativa y con ellos no era posible realizar los distintos análisis que hemos propuesto en las metodologías.

# Metodologías

# Resultados

# Conclusión

En conclusión, el Emiliano vale pico, pero no tanto como Aravena.

# Bibliografía (EDITAR DESPUÉS)

1. https://www.fundaciontrascender.cl/2018/12/18/que-es-pobreza-multidimensional/
2. Libro de códigos Base de Datos Casen 2017


